//
//  LocalizationEnum.swift
//  SmartLocalization
//
//  Created by Danqiang_Zhao on 2/28/19.
//  Copyright © 2019 Danqiang_Zhao. All rights reserved.
//

import Foundation

enum LocalizationEnum: String {
    case Albania = "AL"
    case United_Arab_Emirates = "AE"
    case Argentina = "AR"
    case Australia = "AU"
    case Austria = "AT"
    case Belgium = "BE"
    case Bulgaria = "BG"
    case Bahrain = "BH"
    case Bosnia_and_Herzegovina = "BA"
    case Belarus = "BY"
    case Bolivia = "BO"
    case Brazil = "BR"
    case Canada = "CA"
    case Switzerland = "CH"
       case Chile = "CL"
    case China = "CN"
    case Colombia = "CO"
    case Costa_Rica = "CR"
    case Cyprus = "CY"
    case Czech_Republic = "CZ"
    case Germany = "DE"
    case Denmark = "DK"
    case Dominican_Republic = "DO"
    case Algeria = "DZ"
    case Ecuador = "EC"
    case Egypt = "EG"
    case Spain = "ES"
    case Estonia = "EE"
    case Finland = "FI"
    case France = "FR"
    case United_Kingdom = "GB"
    case Greece = "GR"
    case Guatemala = "GT"
    case Hong_Kong = "HK"
    case Honduras = "HN"
    case Croatia = "HR"
    case Hungary = "HU"
    case Indonesia = "ID"
    case India = "IN"
    case Ireland = "IE"
    case Iraq = "IQ"
    case Iceland = "IS"
    case Israel = "IL"
    case Italy = "IT"
    case Jordan = "JO"
    case Japan = "JP"
    case South_Korea = "KR"
    case Kuwait = "KW"
    case Lebanon = "LB"
    case Libya = "LY"
    case Lithuania = "LT"
    case Luxembourg = "LU"
    case Latvia = "LV"
    case Morocco = "MA"
    case Mexico = "MX"
    case Macedonia = "MK"
    case Malta = "MT"
    case Montenegro = "ME"
    case Malaysia = "MY"
    case Nicaragua = "NI"
    case Netherlands = "NL"
    case Norway = "NO"
    case New_Zealand = "NZ"
    case Oman = "OM"
    case Panama = "PA"
    case Peru = "PE"
    case Philippines = "PH"
    case Poland = "PL"
    case Puerto_Rico = "PR"
    case Portugal = "PT"
    case Paraguay = "PY"
    case Qatar = "QA"
    case Romania = "RO"
    case Russia = "RU"
    case Saudi_Arabia = "SA"
    case Serbia_and_Montenegro = "CS"
    case Sudan = "SD"
    case Singapore = "SG"
    case El_Salvador = "SV"
    case Serbia = "RS"
    case Slovakia = "SK"
    case Slovenia = "SI"
    case Sweden = "SE"
    case Syria = "SY"
    case Thailand = "TH"
    case Tunisia = "TN"
    case Turkey = "TR"
    case Taiwan = "TW"
    case Ukraine = "UA"
    case Uruguay = "UY"
    case United_States = "US"
    case Venezuela = "VE"
    case Vietnam = "VN"
    case Yemen = "YE"
    case South_Africa = "ZA"
}
